import {
  ApplicationStatus,
  ExperienceLevel,
  JobStatus,
  JobType,
  WorkplaceType,
} from '@prisma/client';

export const CORE_EMPLOYER = {
  name: 'TechCorp Admin',
  email: 'employer@gmail.com',
  password: 'employer1234',
};

export const CORE_EMPLOYER_PROFILE = {
  companyName: 'TechCorp',
  companyLogo: '',
  industry: 'Information Technology',
  headquartersLocation: 'Bangalore, India',
  website: 'https://techcorp.example.com',
  companyDescription:
    'A leading technology company specializing in elegant software solutions.',
  contactEmail: 'hr@techcorp.example.com',
  contactPhone: '+91 9876543210',
};

export interface SeedJob {
  title: string;
  companyName: string;
  location: string;
  workplaceType: WorkplaceType;
  jobType: JobType;
  minSalary: number;
  maxSalary: number;
  currency: string;
  experienceLevel: ExperienceLevel;
  description: string;
  requirements: string[];
  responsibilities: string[];
  applicationDeadline: string;
  status: JobStatus;
  skills: string[];
}

export const JOB_LISTING_SEEDS: SeedJob[] = [
  {
    title: 'Frontend Developer',
    companyName: 'TechCorp',
    location: 'Bangalore',
    workplaceType: 'remote',
    jobType: 'full_time',
    minSalary: 600000,
    maxSalary: 900000,
    currency: 'INR',
    experienceLevel: 'junior',
    description: 'Build responsive UI using React and Tailwind.',
    requirements: [
      'Strong proficiency in JavaScript (ES6+) and TypeScript',
      'Hands-on experience with React.js and functional components',
      'Knowledge of modern CSS frameworks like Tailwind CSS or Styled Components',
      'Familiarity with state management libraries (Redux, Zustand, or Context API)',
      'Understanding of Git version control and collaborative workflows',
      'Basic understanding of SEO principles and web performance',
    ],
    responsibilities: [
      'Develop and maintain reusable UI components and libraries',
      'Translate Figma designs into high-quality, responsive code',
      'Collaborate with backend engineers to integrate RESTful APIs',
      'Perform unit testing and assist in debugging UI issues',
      'Optimize web applications for maximum speed and scalability',
      'Participate in daily stand-ups and sprint planning sessions',
    ],
    applicationDeadline: '2026-04-30',
    status: 'open',
    skills: ['JavaScript', 'TypeScript', 'React', 'Tailwind CSS'],
  },
  {
    title: 'Backend Developer',
    companyName: 'CodeBase',
    location: 'Hyderabad',
    workplaceType: 'hybrid',
    jobType: 'full_time',
    minSalary: 800000,
    maxSalary: 1200000,
    currency: 'INR',
    experienceLevel: 'intermediate',
    description: 'Develop scalable APIs using Node.js and PostgreSQL.',
    requirements: [
      'Proven experience with Node.js and Express.js',
      'Strong understanding of relational databases like PostgreSQL or MySQL',
      'Experience designing and documenting RESTful and GraphQL APIs',
      'Familiarity with Redis for caching and session management',
      'Knowledge of authentication protocols like JWT and OAuth2',
      'Understanding of Docker and containerization basics',
    ],
    responsibilities: [
      'Design and implement scalable backend architectures',
      'Write clean, maintainable, and well-documented server-side code',
      'Optimize database queries for performance and reliability',
      'Implement security and data protection measures',
      'Collaborate with frontend teams to define API contracts',
      'Troubleshoot and resolve production bottlenecks and bugs',
    ],
    applicationDeadline: '2026-05-10',
    status: 'open',
    skills: ['Node.js', 'Express', 'PostgreSQL', 'Redis'],
  },
  {
    title: 'Full Stack Developer',
    companyName: 'InnovateX',
    location: 'Remote',
    workplaceType: 'remote',
    jobType: 'full_time',
    minSalary: 1000000,
    maxSalary: 1500000,
    currency: 'INR',
    experienceLevel: 'senior',
    description: 'Work across frontend and backend systems.',
    requirements: [
      'Expertise in the MERN or T3 stack (Next.js, TypeScript, Prisma/Drizzle)',
      'Strong foundation in System Design and Scalability',
      'Experience with CI/CD pipelines and automated testing (Jest, Cypress)',
      'In-depth knowledge of cloud providers (AWS, GCP, or Azure)',
      'Ability to write complex SQL queries and optimize DB schemas',
      'Excellent communication and technical leadership skills',
    ],
    responsibilities: [
      'Lead the development of end-to-end features from concept to deployment',
      'Provide technical mentorship to junior and intermediate developers',
      'Conduct rigorous code reviews and enforce best practices',
      'Collaborate with product owners to define technical roadmaps',
      'Oversee infrastructure setup and monitoring (CloudWatch, Sentry)',
      'Draft technical documentation and system architecture diagrams',
    ],
    applicationDeadline: '2026-05-20',
    status: 'open',
    skills: ['Next.js', 'TypeScript', 'Prisma', 'AWS'],
  },
  {
    title: 'UI/UX Designer',
    companyName: 'Designify',
    location: 'Mumbai',
    workplaceType: 'on_site',
    jobType: 'full_time',
    minSalary: 500000,
    maxSalary: 800000,
    currency: 'INR',
    experienceLevel: 'junior',
    description: 'Design modern and user-friendly interfaces.',
    requirements: [
      'Proficiency in Figma, Adobe XD, or Sketch',
      'Understanding of typography, color theory, and layout grids',
      'Portfolio showcasing web and mobile interface designs',
      'Basic understanding of HTML/CSS capabilities and limitations',
      'Familiarity with prototyping tools like Protopie or Framer',
      'Strong empathy and user-centric mindset',
    ],
    responsibilities: [
      'Create low-fidelity wireframes and high-fidelity mockups',
      'Develop interactive prototypes for user testing and stakeholder demos',
      'Conduct user research and usability testing to validate designs',
      'Maintain and expand the company’s internal Design System',
      'Prepare design handoff documentation for the engineering team',
      'Iterate on designs based on user feedback and analytics data',
    ],
    applicationDeadline: '2026-04-25',
    status: 'closed',
    skills: ['Figma', 'Adobe XD', 'Sketch', 'Prototyping'],
  },
  {
    title: 'DevOps Engineer',
    companyName: 'CloudOps',
    location: 'Pune',
    workplaceType: 'hybrid',
    jobType: 'full_time',
    minSalary: 900000,
    maxSalary: 1400000,
    currency: 'INR',
    experienceLevel: 'intermediate',
    description: 'Manage CI/CD pipelines and cloud infra.',
    requirements: [
      'Strong experience with AWS (EC2, S3, RDS, Lambda)',
      'Expertise in Docker and Kubernetes (EKS/GKE)',
      'Hands-on experience with Infrastructure as Code (Terraform or CloudFormation)',
      'Proficiency in scripting languages like Python or Bash',
      'Knowledge of monitoring tools like Prometheus, Grafana, or Datadog',
      'Experience setting up CI/CD with GitHub Actions, Jenkins, or GitLab CI',
    ],
    responsibilities: [
      'Automate the deployment and scaling of cloud-native applications',
      'Implement and manage robust logging and observability solutions',
      'Maintain system security through IAM roles and network policies',
      'Optimize cloud infrastructure for cost and performance',
      'Manage database backups, recovery, and disaster planning',
      'Support development teams in resolving deployment bottlenecks',
    ],
    applicationDeadline: '2026-05-15',
    status: 'open',
    skills: ['AWS', 'Docker', 'Kubernetes', 'Terraform'],
  },
  {
    title: 'Data Analyst',
    companyName: 'DataWorks',
    location: 'Delhi',
    workplaceType: 'on_site',
    jobType: 'full_time',
    minSalary: 400000,
    maxSalary: 700000,
    currency: 'INR',
    experienceLevel: 'fresher',
    description: 'Analyze datasets and generate insights.',
    requirements: [
      'Advanced knowledge of SQL for data extraction and manipulation',
      'Proficiency in Microsoft Excel (VLOOKUP, Pivot Tables, Macros)',
      'Experience with data visualization tools like Tableau, Power BI, or Looker',
      'Basic understanding of Python (Pandas/NumPy) or R for analysis',
      'Strong analytical and problem-solving skills',
      'Degree in Mathematics, Statistics, Computer Science, or Economics',
    ],
    responsibilities: [
      'Clean and validate data to ensure accuracy and consistency',
      'Build and maintain automated dashboards for key business metrics',
      'Analyze trends and patterns to support strategic decision-making',
      'Present findings to stakeholders through clear and concise reports',
      'Identify areas for process improvement based on data insights',
      'Collaborate with data engineers to streamline data collection',
    ],
    applicationDeadline: '2026-04-28',
    status: 'open',
    skills: ['SQL', 'Excel', 'Tableau', 'Python'],
  },
  {
    title: 'Mobile App Developer',
    companyName: 'Appify',
    location: 'Remote',
    workplaceType: 'remote',
    jobType: 'contract',
    minSalary: 700000,
    maxSalary: 1100000,
    currency: 'INR',
    experienceLevel: 'intermediate',
    description: 'Build cross-platform mobile apps.',
    requirements: [
      'Solid experience with React Native and the Expo ecosystem',
      'Knowledge of mobile-specific design patterns and platform guidelines (iOS/Android)',
      'Experience with mobile state management (Redux, MobX, or Jotai)',
      'Familiarity with publishing apps to Apple App Store and Google Play Store',
      'Ability to bridge native modules using Swift/Kotlin if required',
      'Experience with push notifications and deep linking',
    ],
    responsibilities: [
      'Develop and ship high-performance features for cross-platform apps',
      'Optimize app performance, including memory usage and startup time',
      'Integrate third-party SDKs and RESTful APIs smoothly',
      'Handle offline data storage and synchronization logic',
      'Write clean, reusable code and maintain unit tests for mobile',
      'Collaborate with QA to identify and resolve device-specific bugs',
    ],
    applicationDeadline: '2026-05-18',
    status: 'open',
    skills: ['React Native', 'Expo', 'Redux', 'Mobile Development'],
  },
  {
    title: 'QA Engineer',
    companyName: 'Testify',
    location: 'Chennai',
    workplaceType: 'hybrid',
    jobType: 'full_time',
    minSalary: 500000,
    maxSalary: 800000,
    currency: 'INR',
    experienceLevel: 'junior',
    description: 'Ensure product quality through testing.',
    requirements: [
      'Experience in Manual Testing methodologies and SDLC',
      'Familiarity with automation tools like Selenium, Cypress, or Playwright',
      'Knowledge of API testing tools such as Postman or Insomnia',
      'Basic understanding of SQL to verify data integrity',
      'Excellent eye for detail and strong documentation skills',
      'Familiarity with bug tracking tools like Jira or Linear',
    ],
    responsibilities: [
      'Design, write, and execute detailed test cases and test plans',
      'Identify, document, and track software defects to resolution',
      'Perform smoke, regression, and exploratory testing on new builds',
      'Develop and maintain automated test scripts for critical flows',
      'Communicate quality risks to product and engineering teams',
      'Verify bug fixes and ensure high product reliability',
    ],
    applicationDeadline: '2026-04-27',
    status: 'open',
    skills: ['Manual Testing', 'Selenium', 'Postman', 'Jira'],
  },
  {
    title: 'Product Manager',
    companyName: 'Prodify',
    location: 'Bangalore',
    workplaceType: 'on_site',
    jobType: 'full_time',
    minSalary: 1200000,
    maxSalary: 1800000,
    currency: 'INR',
    experienceLevel: 'senior',
    description: 'Lead product development and strategy.',
    requirements: [
      'Proven track record in product management for SaaS or consumer apps',
      'Strong understanding of Agile/Scrum methodologies',
      'Ability to interpret complex data and use it to drive product decisions',
      'Excellent stakeholder management and negotiation skills',
      'Experience with product analytics tools like Mixpanel, Amplitude, or Hotjar',
      'Technical background or ability to communicate deeply with engineers',
    ],
    responsibilities: [
      'Define the product vision, strategy, and long-term roadmap',
      'Gather and prioritize product requirements from customers and stakeholders',
      'Write clear and detailed PRDs (Product Requirement Documents)',
      'Work closely with designers and engineers to ensure high-quality delivery',
      'Analyze market trends and competitor products to stay ahead',
      'Launch features, measure impact, and iterate based on user feedback',
    ],
    applicationDeadline: '2026-05-25',
    status: 'open',
    skills: [
      'Product Management',
      'Agile',
      'Data Analysis',
      'Stakeholder Management',
    ],
  },
  {
    title: 'Intern Software Developer',
    companyName: 'StartupHub',
    location: 'Remote',
    workplaceType: 'remote',
    jobType: 'internship',
    minSalary: 150000,
    maxSalary: 300000,
    currency: 'INR',
    experienceLevel: 'fresher',
    description: 'Assist in building web applications.',
    requirements: [
      'Basic understanding of HTML5, CSS3, and modern JavaScript',
      'Familiarity with at least one frontend framework (React, Vue, or Angular)',
      'Basic knowledge of Git and command-line interfaces',
      'Strong willingness to learn and adapt to new technologies',
      'Excellent problem-solving skills and attention to detail',
      'Enrolled in or recently graduated from a CS or related degree',
    ],
    responsibilities: [
      'Assist senior developers in implementing new website features',
      'Write clean and simple code while following established style guides',
      'Help fix UI bugs and improve overall frontend responsiveness',
      'Draft internal documentation for small features and workflows',
      'Participate in code reviews to learn best practices',
      'Contribute to team meetings and share fresh perspectives',
    ],
    applicationDeadline: '2026-04-22',
    status: 'open',
    skills: ['HTML', 'CSS', 'JavaScript', 'React'],
  },
  {
    title: 'Cybersecurity Analyst',
    companyName: 'SecureNet',
    location: 'Bangalore',
    workplaceType: 'hybrid',
    jobType: 'full_time',
    minSalary: 1100000,
    maxSalary: 1600000,
    currency: 'INR',
    experienceLevel: 'intermediate',
    description: 'Protect our digital assets and monitor for threats.',
    requirements: [
      'In-depth knowledge of firewalls and SIEM tools',
      'Experience with penetration testing and vulnerability scans',
      'Certifications like CEH, CISSP, or CompTIA Security+',
      'Strong understanding of TCP/IP and network protocols',
      'Familiarity with compliance frameworks (ISO 27001, GDPR)',
      'Ability to respond to security incidents in real-time',
    ],
    responsibilities: [
      'Monitor network traffic for suspicious activity',
      'Conduct regular security audits and risk assessments',
      'Implement and manage encryption and data protection',
      'Collaborate with IT teams to patch vulnerabilities',
      'Develop and document security policies and procedures',
      'Educate employees on security best practices',
    ],
    applicationDeadline: '2026-06-01',
    status: 'open',
    skills: ['Firewalls', 'Penetration Testing', 'SIEM', 'Incident Response'],
  },
  {
    title: 'AI/ML Engineer',
    companyName: 'DeepLogic',
    location: 'Hyderabad',
    workplaceType: 'remote',
    jobType: 'full_time',
    minSalary: 1800000,
    maxSalary: 2800000,
    currency: 'INR',
    experienceLevel: 'senior',
    description: 'Build and deploy sophisticated machine learning models.',
    requirements: [
      'Masters or PhD in CS, Mathematics, or related field',
      'Expertise in Python, PyTorch, or TensorFlow',
      'Strong foundation in Natural Language Processing (NLP)',
      'Experience deploying models using SageMaker or Vertex AI',
      'Knowledge of vector databases like Pinecone or Milvus',
      'Published research or significant portfolio in AI',
    ],
    responsibilities: [
      'Design and train LLMs for specific business use cases',
      'Optimize model inference for production environments',
      'Curate and preprocess large-scale datasets',
      'Stay updated with latest papers and AI breakthroughs',
      'Mentor junior data scientists and engineers',
      'Collaborate with Product on AI feature feasibility',
    ],
    applicationDeadline: '2026-06-15',
    status: 'open',
    skills: ['Python', 'PyTorch', 'NLP', 'Model Deployment'],
  },
  {
    title: 'HR Manager',
    companyName: 'GrowthX',
    location: 'Kolkata',
    workplaceType: 'on_site',
    jobType: 'full_time',
    minSalary: 700000,
    maxSalary: 1100000,
    currency: 'INR',
    experienceLevel: 'intermediate',
    description: 'Lead recruitment and employee engagement initiatives.',
    requirements: [
      'MBA in Human Resources or equivalent',
      'Experience with HRMS software like Zoho or BambooHR',
      'Excellent interpersonal and communication skills',
      'Understanding of Indian Labor Laws and compliance',
      'Proven track record in tech hiring and talent acquisition',
      'Strong conflict resolution and negotiation skills',
    ],
    responsibilities: [
      'Manage the end-to-end recruitment lifecycle',
      'Design and implement employee wellness programs',
      'Oversee performance management and appraisal cycles',
      'Handle employee grievances and maintain office culture',
      'Draft and update company policies and handbooks',
      'Organize team-building events and activities',
    ],
    applicationDeadline: '2026-05-30',
    status: 'open',
    skills: ['Recruitment', 'Employee Engagement', 'HRMS', 'Labor Laws'],
  },
  {
    title: 'Content Writer',
    companyName: 'WriteWave',
    location: 'Remote',
    workplaceType: 'remote',
    jobType: 'contract',
    minSalary: 300000,
    maxSalary: 500000,
    currency: 'INR',
    experienceLevel: 'junior',
    description: 'Create engaging content for blogs and social media.',
    requirements: [
      'Exceptional command over written English',
      'Understanding of SEO principles and keyword research',
      'Portfolio of published articles or blog posts',
      'Ability to adapt tone for different target audiences',
      'Familiarity with CMS tools like WordPress or Ghost',
      'Knowledge of social media trends and storytelling',
    ],
    responsibilities: [
      'Write 3–4 high-quality blog posts per week',
      'Collaborate with designers for social media copy',
      'Perform research on industry-specific topics',
      'Proofread and edit content for clarity and grammar',
      'Coordinate with the SEO team to optimize articles',
      'Manage the content calendar and deadlines',
    ],
    applicationDeadline: '2026-05-15',
    status: 'open',
    skills: ['Content Writing', 'SEO', 'WordPress', 'Social Media'],
  },
  {
    title: 'Systems Administrator',
    companyName: 'LegacySys',
    location: 'Chennai',
    workplaceType: 'on_site',
    jobType: 'full_time',
    minSalary: 600000,
    maxSalary: 950000,
    currency: 'INR',
    experienceLevel: 'intermediate',
    description: 'Maintain and upgrade our internal IT infrastructure.',
    requirements: [
      'Experience managing Linux and Windows Servers',
      'Knowledge of networking (VLANs, DNS, DHCP)',
      'Hands-on with virtualization tools like VMware or Proxmox',
      'Familiarity with Active Directory and LDAP',
      'Ability to troubleshoot hardware and software issues',
      'Experience with backup and recovery solutions',
    ],
    responsibilities: [
      'Install and configure server hardware and software',
      'Monitor system performance and ensure high uptime',
      'Manage user accounts, permissions, and security',
      'Perform regular data backups and disaster recovery tests',
      'Provide technical support to internal employees',
      'Manage hardware inventory and vendor relations',
    ],
    applicationDeadline: '2026-05-10',
    status: 'open',
    skills: ['Linux', 'Windows Server', 'Networking', 'Virtualization'],
  },
  {
    title: 'Blockchain Developer',
    companyName: 'CryptoForge',
    location: 'Remote',
    workplaceType: 'remote',
    jobType: 'full_time',
    minSalary: 1500000,
    maxSalary: 2500000,
    currency: 'INR',
    experienceLevel: 'senior',
    description: 'Develop smart contracts and decentralized apps.',
    requirements: [
      'Strong experience with Solidity and Ethers.js',
      'Deep understanding of Ethereum and EVM mechanics',
      'Knowledge of DeFi protocols and Layer 2 solutions',
      'Experience with smart contract security and audits',
      'Proficiency in Rust for Solana/Polkadot development',
      'Familiarity with IPFS and decentralized storage',
    ],
    responsibilities: [
      'Architect and deploy secure smart contracts',
      'Build frontend integrations for Web3 applications',
      'Optimize gas costs for blockchain transactions',
      'Monitor on-chain events and data indexing',
      'Collaborate on tokenomics and protocol design',
      'Research emerging blockchain technologies and EIPs',
    ],
    applicationDeadline: '2026-06-20',
    status: 'open',
    skills: ['Solidity', 'Ethers.js', 'Ethereum', 'DeFi'],
  },
  {
    title: 'SEO Specialist',
    companyName: 'RankUp',
    location: 'Ahmedabad',
    workplaceType: 'hybrid',
    jobType: 'full_time',
    minSalary: 450000,
    maxSalary: 750000,
    currency: 'INR',
    experienceLevel: 'junior',
    description: 'Improve our search engine rankings and organic traffic.',
    requirements: [
      'Proficiency in Google Analytics and Search Console',
      'Experience with tools like Ahrefs, SEMrush, or Moz',
      'Understanding of on-page and technical SEO',
      'Knowledge of backlink building strategies',
      'Ability to perform keyword research and gap analysis',
      'Basic understanding of HTML and CSS',
    ],
    responsibilities: [
      'Optimize website content and meta tags',
      'Identify and fix crawl errors and indexing issues',
      'Analyze competitor strategies and link profiles',
      'Track and report on keyword rankings and traffic',
      'Work with content writers on SEO guidelines',
      'Stay updated with Google algorithm changes',
    ],
    applicationDeadline: '2026-05-05',
    status: 'open',
    skills: ['Google Analytics', 'Ahrefs', 'On-page SEO', 'Link Building'],
  },
  {
    title: 'Customer Success Rep',
    companyName: 'UserFirst',
    location: 'Pune',
    workplaceType: 'remote',
    jobType: 'full_time',
    minSalary: 350000,
    maxSalary: 600000,
    currency: 'INR',
    experienceLevel: 'fresher',
    description: 'Help our users get the most value out of our product.',
    requirements: [
      'Excellent verbal and written communication',
      'Problem-solving mindset and patience',
      'Ability to explain technical concepts simply',
      'Experience with CRM tools like Salesforce or HubSpot',
      'Comfortable with video calls and demos',
      'Strong organization and time management',
    ],
    responsibilities: [
      'Onboard new customers and guide them through setup',
      'Respond to user queries via chat, email, and phone',
      'Identify opportunities for upselling or cross-selling',
      'Gather user feedback for the product team',
      'Create help articles and tutorial videos',
      'Proactively reach out to at-risk customers',
    ],
    applicationDeadline: '2026-04-30',
    status: 'open',
    skills: ['Communication', 'Problem Solving', 'CRM', 'Customer Support'],
  },
  {
    title: 'Cloud Architect',
    companyName: 'SkyScale',
    location: 'Bangalore',
    workplaceType: 'remote',
    jobType: 'full_time',
    minSalary: 2500000,
    maxSalary: 4000000,
    currency: 'INR',
    experienceLevel: 'senior',
    description: 'Design and oversee complex cloud infrastructures.',
    requirements: [
      'Extensive experience with AWS, Azure, or GCP at scale',
      'Deep knowledge of microservices and serverless design',
      'Proficiency in multi-cloud and hybrid cloud strategies',
      'Strong understanding of cloud security and compliance',
      'Experience with high-availability and disaster recovery',
      'AWS Certified Solutions Architect (Professional) preferred',
    ],
    responsibilities: [
      'Architect end-to-end cloud solutions for enterprise clients',
      'Lead digital transformation and cloud migration projects',
      'Optimize cloud spend and resource utilization',
      'Define cloud governance and best practice standards',
      'Consult with C-suite stakeholders on technical vision',
      'Conduct architecture reviews and identify risks',
    ],
    applicationDeadline: '2026-07-01',
    status: 'open',
    skills: ['AWS', 'Azure', 'GCP', 'Cloud Architecture', 'Security'],
  },
  {
    title: 'Technical Lead',
    companyName: 'CoreBuild',
    location: 'Remote',
    workplaceType: 'remote',
    jobType: 'full_time',
    minSalary: 2200000,
    maxSalary: 3200000,
    currency: 'INR',
    experienceLevel: 'senior',
    description: 'Lead an engineering squad to deliver high-impact features.',
    requirements: [
      'Strong background in full-stack software development',
      'Experience leading teams and managing delivery timelines',
      'Expertise in architecture patterns and system design',
      'Excellent problem-solving and decision-making skills',
      'Proven ability to mentor and grow engineers',
      'Knowledge of agile processes and sprint management',
    ],
    responsibilities: [
      'Oversee technical execution and code quality for the team',
      'Break down complex requirements into technical tasks',
      'Unblock engineers and resolve technical disputes',
      'Collaborate with Product and Design on roadmaps',
      'Hire and interview for the engineering department',
      'Drive engineering excellence and modern dev practices',
    ],
    applicationDeadline: '2026-06-10',
    status: 'open',
    skills: ['Leadership', 'Full-Stack Development', 'System Design', 'Agile'],
  },
  {
    title: 'Business Development',
    companyName: 'SalesFlow',
    location: 'Mumbai',
    workplaceType: 'on_site',
    jobType: 'full_time',
    minSalary: 500000,
    maxSalary: 900000,
    currency: 'INR',
    experienceLevel: 'junior',
    description: 'Identify new business opportunities and drive growth.',
    requirements: [
      'Strong sales aptitude and communication skills',
      'Ability to build rapport with potential clients',
      'Experience with outbound prospecting and lead gen',
      'Familiarity with CRM and sales automation tools',
      'Resilient attitude and target-driven mindset',
      "Bachelor's degree in Business or related field",
    ],
    responsibilities: [
      'Conduct outbound outreach via cold calls and emails',
      'Nurture leads and book meetings for senior sales staff',
      'Perform market research to identify potential segments',
      'Prepare and deliver compelling sales presentations',
      'Meet and exceed monthly and quarterly sales targets',
      'Maintain accurate records in the sales database',
    ],
    applicationDeadline: '2026-05-20',
    status: 'open',
    skills: ['Sales', 'Lead Generation', 'CRM', 'Communication'],
  },
  {
    title: 'Video Editor',
    companyName: 'CreativeClip',
    location: 'Remote',
    workplaceType: 'remote',
    jobType: 'part_time',
    minSalary: 400000,
    maxSalary: 700000,
    currency: 'INR',
    experienceLevel: 'intermediate',
    description: 'Produce high-quality video content for YouTube and ads.',
    requirements: [
      'Proficiency in Adobe Premiere Pro and After Effects',
      'Experience with motion graphics and color grading',
      'Strong portfolio of edited video content',
      'Ability to tell stories through visual editing',
      'Understanding of video formats for social media',
      'Knowledge of sound design and audio mixing',
    ],
    responsibilities: [
      'Edit raw footage into polished, engaging videos',
      'Add motion graphics, titles, and visual effects',
      'Collaborate with the creative lead on video concepts',
      'Optimize videos for various social media platforms',
      'Manage and organize large amounts of video assets',
      'Incorporate feedback and iterate on video drafts',
    ],
    applicationDeadline: '2026-05-25',
    status: 'open',
    skills: [
      'Adobe Premiere',
      'After Effects',
      'Motion Graphics',
      'Color Grading',
    ],
  },
  {
    title: 'Database Admin',
    companyName: 'DataStore',
    location: 'Pune',
    workplaceType: 'hybrid',
    jobType: 'full_time',
    minSalary: 850000,
    maxSalary: 1300000,
    currency: 'INR',
    experienceLevel: 'intermediate',
    description: 'Ensure the performance and security of our databases.',
    requirements: [
      'Expertise in PostgreSQL or MySQL administration',
      'Experience with NoSQL databases like MongoDB',
      'Strong SQL optimization and tuning skills',
      'Knowledge of database replication and clustering',
      'Familiarity with DB backup and recovery strategies',
      'Understanding of database security and auditing',
    ],
    responsibilities: [
      'Maintain and update database server environments',
      'Optimize queries and schemas for maximum speed',
      'Ensure data integrity and perform regular audits',
      'Manage database access and security permissions',
      'Automate routine database maintenance tasks',
      'Troubleshoot database-related performance issues',
    ],
    applicationDeadline: '2026-05-18',
    status: 'open',
    skills: [
      'PostgreSQL',
      'MySQL',
      'MongoDB',
      'SQL Optimization',
      'Database Security',
    ],
  },
  {
    title: 'SRE',
    companyName: 'ReliableScale',
    location: 'Remote',
    workplaceType: 'remote',
    jobType: 'full_time',
    minSalary: 1600000,
    maxSalary: 2400000,
    currency: 'INR',
    experienceLevel: 'senior',
    description: 'Bridge the gap between development and operations.',
    requirements: [
      'Strong coding skills in Python or Go',
      'Deep understanding of Linux internals and networking',
      'Experience with observability stacks (ELK, TIG)',
      'Expertise in Kubernetes and container orchestration',
      'Knowledge of SLIs, SLOs, and Error Budgets',
      'Proven track record in handling production incidents',
    ],
    responsibilities: [
      'Improve system reliability through automation',
      'Build and maintain monitoring and alerting tools',
      'Participate in an on-call rotation for production systems',
      'Conduct post-mortems and drive root cause analysis',
      'Scale infrastructure to meet growing traffic demands',
      'Design systems to be self-healing and resilient',
    ],
    applicationDeadline: '2026-06-05',
    status: 'open',
    skills: [
      'Python',
      'Go',
      'Kubernetes',
      'Observability',
      'Incident Management',
    ],
  },
];

export const MY_JOB_SEEDS: SeedJob[] = [
  {
    title: 'Full Stack Developer',
    companyName: 'InnovateX',
    location: 'Remote',
    workplaceType: 'remote',
    jobType: 'full_time',
    minSalary: 1000000,
    maxSalary: 1500000,
    currency: 'INR',
    experienceLevel: 'senior',
    description: 'Work across frontend and backend systems.',
    requirements: [
      'Expertise in the MERN or T3 stack (Next.js, TypeScript, Prisma/Drizzle)',
      'Strong foundation in System Design and Scalability',
      'Experience with CI/CD pipelines and automated testing (Jest, Cypress)',
      'In-depth knowledge of cloud providers (AWS, GCP, or Azure)',
      'Ability to write complex SQL queries and optimize DB schemas',
      'Excellent communication and technical leadership skills',
    ],
    responsibilities: [
      'Lead the development of end-to-end features from concept to deployment',
      'Provide technical mentorship to junior and intermediate developers',
      'Conduct rigorous code reviews and enforce best practices',
      'Collaborate with product owners to define technical roadmaps',
      'Oversee infrastructure setup and monitoring (CloudWatch, Sentry)',
      'Draft technical documentation and system architecture diagrams',
    ],
    applicationDeadline: '2026-05-20',
    status: 'open',
    skills: ['Next.js', 'TypeScript', 'Prisma', 'AWS'],
  },
  {
    title: 'UI/UX Designer',
    companyName: 'Designify',
    location: 'Mumbai',
    workplaceType: 'on_site',
    jobType: 'full_time',
    minSalary: 500000,
    maxSalary: 800000,
    currency: 'INR',
    experienceLevel: 'junior',
    description: 'Design modern and user-friendly interfaces.',
    requirements: [
      'Proficiency in Figma, Adobe XD, or Sketch',
      'Understanding of typography, color theory, and layout grids',
      'Portfolio showcasing web and mobile interface designs',
      'Basic understanding of HTML/CSS capabilities and limitations',
      'Familiarity with prototyping tools like Protopie or Framer',
      'Strong empathy and user-centric mindset',
    ],
    responsibilities: [
      'Create low-fidelity wireframes and high-fidelity mockups',
      'Develop interactive prototypes for user testing and stakeholder demos',
      'Conduct user research and usability testing to validate designs',
      'Maintain and expand the company’s internal Design System',
      'Prepare design handoff documentation for the engineering team',
      'Iterate on designs based on user feedback and analytics data',
    ],
    applicationDeadline: '2026-04-25',
    status: 'closed',
    skills: ['Figma', 'Adobe XD', 'Sketch', 'Prototyping'],
  },
  {
    title: 'DevOps Engineer',
    companyName: 'CloudOps',
    location: 'Pune',
    workplaceType: 'hybrid',
    jobType: 'full_time',
    minSalary: 900000,
    maxSalary: 1400000,
    currency: 'INR',
    experienceLevel: 'intermediate',
    description: 'Manage CI/CD pipelines and cloud infra.',
    requirements: [
      'Strong experience with AWS (EC2, S3, RDS, Lambda)',
      'Expertise in Docker and Kubernetes (EKS/GKE)',
      'Hands-on experience with Infrastructure as Code (Terraform or CloudFormation)',
      'Proficiency in scripting languages like Python or Bash',
      'Knowledge of monitoring tools like Prometheus, Grafana, or Datadog',
      'Experience setting up CI/CD with GitHub Actions, Jenkins, or GitLab CI',
    ],
    responsibilities: [
      'Automate the deployment and scaling of cloud-native applications',
      'Implement and manage robust logging and observability solutions',
      'Maintain system security through IAM roles and network policies',
      'Optimize cloud infrastructure for cost and performance',
      'Manage database backups, recovery, and disaster planning',
      'Support development teams in resolving deployment bottlenecks',
    ],
    applicationDeadline: '2026-05-15',
    status: 'open',
    skills: ['AWS', 'Docker', 'Kubernetes', 'Terraform'],
  },
  {
    title: 'Data Analyst',
    companyName: 'DataWorks',
    location: 'Delhi',
    workplaceType: 'on_site',
    jobType: 'full_time',
    minSalary: 400000,
    maxSalary: 700000,
    currency: 'INR',
    experienceLevel: 'fresher',
    description: 'Analyze datasets and generate insights.',
    requirements: [
      'Advanced knowledge of SQL for data extraction and manipulation',
      'Proficiency in Microsoft Excel (VLOOKUP, Pivot Tables, Macros)',
      'Experience with data visualization tools like Tableau, Power BI, or Looker',
      'Basic understanding of Python (Pandas/NumPy) or R for analysis',
      'Strong analytical and problem-solving skills',
      'Degree in Mathematics, Statistics, Computer Science, or Economics',
    ],
    responsibilities: [
      'Clean and validate data to ensure accuracy and consistency',
      'Build and maintain automated dashboards for key business metrics',
      'Analyze trends and patterns to support strategic decision-making',
      'Present findings to stakeholders through clear and concise reports',
      'Identify areas for process improvement based on data insights',
      'Collaborate with data engineers to streamline data collection',
    ],
    applicationDeadline: '2026-04-28',
    status: 'open',
    skills: ['SQL', 'Excel', 'Tableau', 'Python'],
  },
];

export interface SeedApplication {
  jobTitle: string;
  applicantName: string;
  applicantEmail: string;
  status: ApplicationStatus;
  resumeUrl: string;
  coverLetter: string;
}

export const APPLICATION_SEEDS: SeedApplication[] = [
  {
    jobTitle: 'Full Stack Developer',
    applicantName: 'Alice Johnson',
    applicantEmail: 'alice.j@example.com',
    status: 'pending',
    resumeUrl: '#',
    coverLetter:
      'I am a full-stack engineer with 3 years of experience in Next.js and backend API development.',
  },
  {
    jobTitle: 'UI/UX Designer',
    applicantName: 'Bob Smith',
    applicantEmail: 'bob.smith@example.com',
    status: 'pending',
    resumeUrl: '#',
    coverLetter:
      'I can contribute user-centered design systems and polished interaction design.',
  },
  {
    jobTitle: 'DevOps Engineer',
    applicantName: 'Diana Prince',
    applicantEmail: 'diana.p@example.com',
    status: 'pending',
    resumeUrl: '#',
    coverLetter:
      'My cloud and CI/CD experience with AWS and Kubernetes aligns with this role.',
  },
  {
    jobTitle: 'Data Analyst',
    applicantName: 'Edward Elric',
    applicantEmail: 'ed.elric@example.com',
    status: 'pending',
    resumeUrl: '#',
    coverLetter:
      'Experienced in SQL and dashboards with strong ownership and analytical thinking.',
  },
];
